bocoup/threeflows

src/server/index.js
src/server/service/roles/endpoints.js
src/server/util/api.js
test/server/util/api.test.js

* Using `asyncMiddleware` wrapper you just `throw error` and the error object if it has a .status will use that .status - otherwise defaulting to **500** ![500 Internal Service Error](https://http.cat/500)
* `app.use()` with a 3 param middleware (req, res, next) will catch ALL UNROUTED REQUESTS and "throw" `next(error)` a 404 error
* `app.use(errorHandler)` is a 4 param middleware (error, req, res, next) which only is called when a previous middleware has an error state, and handles sending a JSON error!

Update error handling in middlewares

---

client/.storybook/webpack.config.js
client/webpack.config.js
package.json
test/server/util/api.test.js
test/server/util/sqlHelpers.test.js

I accidentally pushed a previous change to the `teacher-moments` branch (sorry!) that moved `client` and `server` out of `src` and deletes `src` since we had previously decided it was unnecessary nesting. This PR is to fix relative paths after that change.

Fix relative paths without src

---

.eslintrc.json
client/components/editor/index.jsx
client/components/scenarioEditor/index.jsx
client/components/scenarioEditor/scenarioEditor.css
client/components/slideEditor/index.jsx
client/routes/index.jsx
client/webpack.config.js
server/service/scenarios/endpoints.js

@gnarf this PR adds the editor components in the front end as tabs and hooks up the scenario title and description fields to the API to save new entries.
I have also added some front end error handling, since we prevent saving scenarios without a title and description in the database currently. One thing to note: This doesn't tackle editing an existing post currently, so switching to the slides tab or another page will make you loose your scenario content in the "Moment" tab. Open to suggestions to handling that (or anything) better though!

Hook up scenarios UI for creating new scenarios

---

client/components/createAccount/index.jsx
client/components/editor/editor.css
client/components/login/index.jsx
client/components/scenariosList/index.jsx
client/routes/index.jsx
server/service/authentication.js
server/service/scenarios/db.js
server/util/authenticationHelpers.js

I fixed the previous errors that I was running into! The proposed changes now in this PR:
- Use Semantic UI for the login UI
- Add a component to create an account in the front end, hits auth API to add user in the database
- Some tweaks on the backend to fix some errors, clean up code
One downside I'm finding is that a user isn't staying logged in if I refresh the page. That can be tackled in another PR though
Login form
Create account form

Create account UI

---

client/components/createAccount/index.jsx
client/components/login/index.jsx
client/components/scenariosList/index.jsx
client/index.js
client/reducers/login.js
client/routes/index.jsx
client/util/session.js
server/service/authentication.js
server/util/authenticationHelpers.js

@gnarf this will persist a user after they log in, but I didn't have time to fix `client/routes/index.jsx` so that it displayed "Log in" or "Log out" (depending on the state) without a full refresh of the page. 
- The next step is to upgrade this to use JSON web tokens: 
- Create `jwt` on log-in or sign-up, 
- Respond with `jwt` in `res.session.user`
- Store `jwt` in `localStorage` for some period of time (encrypted?)
- Send `jwt` in headers for all requests that need authorization
For now, this gets us basic persistence across refreshes, reloads and new tabs. Any changes that need to be made will likely have to be made directly as new commits—I can't guarantee that I will have time to do follow ups from reviews.

Basic persistance for logged in users.

---

client/components/Editor/index.jsx
client/components/ScenarioEditor/index.jsx

@gnarf @rwaldron this covers Rachel's user testing feedback that it would be nice to see the slides tab after saving a scenario. I made this the case only for new scenarios, but let me know if it should always happen.
Proposed changes:
- Add post submit callback
- Redirect to edit scenario in editor and focus slides tab when saving a scenario for the first time
- Add onTabChange event to set the active tab if a user clicks on a different one

Switch to slides tab when saving new scenario

---

client/components/Editor/Slides.jsx
client/components/Editor/editor.css
client/components/Editor/index.jsx
client/components/ScenarioEditor/index.jsx
client/components/ScenarioEditor/scenarioEditor.css

@gnarf @rwaldron here is my PR for adding a re-usable component for displaying messages in the editor. It ended up being a little more complicated than I had hoped because I needed to switch to Semantic UI's `Menu` component in order to have a right-aligned string next to the tabs. So some of these changes are re-creating the builtin display logic we used to get for free with the `Tab` component. 
Another note, I switched to using `this.state.scenarioId` or `this.props.match.params.id`  instead of `this.state.isNewScenario` because state didn't always seem to be mounted when I needed it.
Let me know what you think and if you have any questions!

Editor message component

---

client/components/Editor/index.jsx

@rwaldron @evmiguel @gnarf I thought I had merged this fix in earlier, but then realized it was missing even from the git history 😅 
In any case, this fixes an issue where if you first create a moment and then try to go back to the "Moment" tab, it will be empty and try to save a new moment on submit.

Clear cached new scenario values on first save

---

client/components/Scenario/ContentSlide.jsx
client/components/Scenario/DescriptionSlide.jsx
client/components/Scenario/Scenario.css
client/components/Scenario/index.jsx
client/components/SlideComponentsList/SlideComponentsList.css
client/components/SlideComponentsList/index.jsx

We got full screen slides!!
These changes:
- allow only one slide to be visible at a time in the frontend view of scenarios
- allows all slides to be visible in the editor preview
- advances slides on click in scenario run and not in preview

Fullscreen slides

---

server/service/scenarios/endpoints.js

This PR fixes the bug that appears when saving a category for the first time, the categories are not saved.

bug fix: save categories on PUT

---

client/actions/index.js
client/actions/types.js
client/components/AccountAdmin/UserRows.jsx
client/components/AccountAdmin/index.jsx
client/components/CreateAccount/index.jsx
client/reducers/admin.js
client/reducers/index.js
client/routes/index.jsx
server/migrations/20191107192140-user-role-view.js
server/migrations/sql/20191107192140-user-role-view.sql
server/service/roles/db.js
server/service/roles/endpoints.js
server/service/roles/index.js

@evmiguel @gnarf @rwaldron here is a PR for adding an admin UI for editing user roles. 
My proposed changes:
- Add account admin components and related Redux action, reducer
- Fixes login form bug where username is required (it shouldn't be, right? Like if someone just wants to use their email address? Let me know if I have that wrong)
- Adds a SQL view for getting all users and aggregating their roles (currently each user's role is a separate row in `user_role`
- Adjust server roles routes to use the req.body and req.session for wherever we need user information and not route params.
Let me know what you think! Currently it auto saves with no messaging, which I know users didn't love before. However I'm wondering if TM admins would be more comfortable with auto-saving.

Add admin UI for editing user roles

---

client/components/ScenarioEditor/index.jsx

This fixes the very broken "Create A Moment" view

ScenarioEditor: only auto save after the scenario has been created by the user

---

client/components/Editor/index.jsx
client/components/ScenarioEditor/index.jsx
client/components/ScenariosList/ScenariosList.css
client/components/ScenariosList/index.jsx
client/reducers/scenario.js
server/service/scenarios/endpoints.js
server/service/scenarios/index.js
server/service/scenarios/slides/db.js
server/service/scenarios/slides/endpoints.js
server/service/scenarios/slides/index.js

@evmiguel @rwaldron here is my PR for adding forking functionality, let me know what you think of it! My proposed changes:
- Add "copy" button to the UI and pass some of the original scenario's data to the copy via `location.state`
- A `copyScenario` function that creates a new scenario with this passed data, gets the original slides and saves that slides data to the new scenario as well
- Add an endpoint for bulk saving slides
- Small amount of refactoring

Add copy button, logic, endpoint for saving multiple slides

---

client/components/Slide/Components/ResponseRecall/Display.jsx

Response Recall: text display preserves newlines

---

client/components/Slide/Components/AudioResponse/Display.jsx
client/components/Slide/Components/AudioResponse/Editor.jsx
client/components/Slide/Components/AudioResponse/index.js

In Chrome: 
In Mobile Safari: 
In the editor:

Audio Response: update to match ui of other response components

---

client/components/ScenariosList/ScenariosList.css
client/components/ScenariosList/index.jsx
client/routes/Nav.css
client/routes/Navigation.jsx
client/routes/Routes.jsx
client/routes/index.jsx

@evmiguel @rwaldron this PR fixes our biggest mobile styling issues, namely no mobile friendly menu and uncentered scenario cards.
Proposed changes:
- Style changes for centering scenarios on the front end
- Add DesktopNav and MobileNav components. The mobile one includes a button for expanding/closing on click using handy dandy React Hooks!
- Refactor the menu to have most of its components in separate files

Add mobile menu and fix some mobile stylings

---

client/components/Scenario/Scenario.css

Run: use a wider card to fill more space on mobile view

---

client/components/Scenario/ContentSlide.jsx
client/components/Slide/Components/AudioResponse/Card.jsx
client/components/Slide/Components/AudioResponse/Display.jsx
client/components/Slide/Components/AudioResponse/Editor.jsx
client/components/Slide/Components/AudioResponse/index.js
client/components/Slide/Components/MultiButtonResponse/Display.jsx
client/components/Slide/Components/MultiButtonResponse/Editor.jsx
client/components/Slide/Components/MultiButtonResponse/index.js
client/components/Slide/Components/PromptRequiredLabel/PromptRequiredLabel.css
client/components/Slide/Components/PromptRequiredLabel/index.jsx
client/components/Slide/Components/TextResponse/Display.jsx
client/components/Slide/Components/TextResponse/Editor.jsx
client/components/Slide/Components/TextResponse/index.js

This PR relies on [Participant Run: simplify response, don't pave over responses with a skip, adds isSkip property to responses](https://github.com/bocoup/threeflows/pull/148) and must be rebased once that lands. 
There was a bug that allowed response prompts to be left empty when the "Submit" button was pressed, effectively by-passing the "intentional Skip" button. Since we can't know what prompts will need to be "required", this PR adds a checkbox to prompt components that allow the author to mark a prompt as "required". On the front end, ContentSlide will determine which components it has that are required and keep track of input to those components, releasing their pending "lock" when they have been satisfied. Once all pending "locks" are released, the "Submit" button will become …

Bug: don't allow prompt response submission when required prompts are present, unless explicitly "skipped"

---

client/actions/index.js
client/components/ConfirmAuth/index.jsx
client/components/Login/index.jsx
client/components/ScenarioEditor/index.jsx
client/components/ScenariosList/DeletedCard.jsx
client/components/ScenariosList/ScenarioCard.jsx
client/components/ScenariosList/ScenarioEntries.jsx
client/components/ScenariosList/index.jsx
client/reducers/login.js
client/routes/Navigation.jsx
client/routes/Routes.jsx
client/util/session.js
server/migrations/20191125213104-role-permission.js
server/migrations/sql/20191125213104-role-permission.sql
server/package.json
server/seed/permissions.json
server/seed/rolePermissions.js
server/service/roles/db.js
server/service/roles/endpoints.js
server/service/roles/index.js
server/service/scenarios/endpoints.js

@rwaldron here is my PR for gating front end features for users based on their role or whether they're the author of a scenario. Let me know what you think, and I can also go over these in person if it's a lot of changes to take in!
Steps to test:
- Pull down branch and run `yarn db-migrate-up` to add the permissions table.
- Run `seed:permissions` in the `/server` directory to seed permissions in that table (I didn't make this a root directory yarn command, but I can). 
- Try users with different roles and who are the authors of some scenarios and not others.
My proposed changes:
- Add `ConfrimAuth` component that can wrap around nav items and other components and check whether a user should have access or not. If not, nothing is rendered.
- Add `role_permission` table to store what …

Add component for front end user auth

---

client/components/ScenarioEditor/index.jsx
client/components/ScenarioEditor/scenarioEditor.css

- Removes unused style
- Add min-width
- Add flex-wrap: nowrap
- Widen Grid Columns
The min-width prevents the "Categories" from looking like this: 
But when you set a min-width, it could result in this: 
So you must set `flex-wrap: nowrap`.

Scenario Editor: widen title, description, category.

---

client/components/Scenario/EntrySlide.css
client/components/Scenario/EntrySlide.jsx

I just determined that this was actually unnecessary.

EntrySlide: remove entryslide__consent-outer-container

---

README.md

Main change is to add these instructions: 
* start teacher moments via `yarn dev` with the correct env vars set
* make a new user account
* enter `psql` as the tm user by typing `psql` with the correct env vars
* type: `SELECT * FROM users;` to find the id find the "id" of the user you created
* type: `INSERT INTO user_role(role, user_id) VALUES ('super_admin', 1);` replacing 1 wit the id is of the user you just created.
* exit psql with a \q
* with the correct env vars for the project run `cd server && yarn seed:permissions`
* `cd ../`
* `yarn dev`

fix typo in db-migrate-up and add instructions for seeding a super_admin

---

client/components/ScenariosList/index.jsx
client/routes/Navigation.jsx
client/routes/RouteComponents.jsx
client/routes/Routes.jsx
server/service/scenarios/db.js
server/service/scenarios/endpoints.js
server/service/scenarios/index.js

@rwaldron @isaacdurazo this PR adds a filtering capability to the home page using a dropdown in the main nav. These are the current options:
And the asana task is here for checking what users should see when: https://app.asana.com/0/1127815256483386/1150836802035131
Steps for testing:
- Start as a logged out user. You should see the drop down options for "Official" and "Community" moments
- Log in as a participant user. You should see the same options plus "Completed Moments", which shows all the moments your user has run.
- Log in as a researcher, facilitator, admin or super admin. You will see the above plus "My Moments" which are the moments your user has authored.
My proposed code changes:
- Expand the category filtering logic in `ScenariosList/index` to account for the four …

Add filtering to homepage for categories, author, user completed moments

---

client/routes/Navigation.jsx

Short and sweet! This removes the "Data Export" menu item from the main nav. 
Steps to test:
- load home page and confirm "Data Export" isn't in the nav
- Click "Cohorts Management" and confirm it's still available

Remove 'Data Export' from the nav

---

client/components/ScenariosList/ScenarioCard.jsx

Proposed changes:
- Check if a moment's categories include the string "official"
- Add a checkmark icon if so
Steps to test:
- Confirm listings of scenarios have the checkmark if they're official 
- Confirm they don't if they're not

Add checkmark icon to official scenarios

---

client/actions/response.js

We don't responses to stick around in client side storage after they are submitted. Doing so will have a bizarre outcome: you will see them the next time you do a run of that scenario.

Bug: Clear responses from localstorage once they are submitted.

---

client/components/Slide/Components/AudioResponse/Display.jsx
client/components/Slide/Components/AudioResponse/index.js

Fallback view: 
Before: 
After: 
-----------------
Audio Prompt reference:

Bug: Display "prompt" in AudioResponse Display fallback

---

client/components/Facilitator/Components/Cohorts/Cohort.jsx

To avoid confusion with features that DO work, I want to hide these not-yet-functional buttons
Before: 
After:

Cohort: temporarily hide non-functional buttons in main cohort view

---

client/actions/response.js
client/components/Facilitator/Components/Cohorts/Cohort.jsx
client/components/Scenario/ContentSlide.jsx
client/components/SlideComponentsList/index.jsx
client/package.json
client/util/session.js
yarn.lock

This will make our use of local persistence a bit more robust.
Test 1: 
1. Run a scenario that has a text prompt, type something into it, but don't hit submit, then refresh the page. Is it still there?
2. Hit submit, move on and complete/finish the scenario 
3. Re run the scenario, when you arrive at the text prompt, is your old entry there or is it clear?
Test 2: 
1. Go to a cohort as a participant, does "My Cohort" persist the cohort you were invited to?
Test 3: 
1. When you're logged in, do you stay logged in across all pages?

Dependency: use "local-storage-fallback" instead of directly using "localStorage"

---

client/components/Scenario/Scenario.css

Run: don't let scenario slide text extend beyond card boundary for very long text

---

server/migrations/20191211193451-cascade-user-deletion.js
server/migrations/sql/20191211193451-cascade-user-deletion.sql
test/load/participant-scenario-run.yml

Proposed changes in this PR:
- Add a migration to change the foreign key constraint on `user_role` table to allow us to delete users. This will be important for cleaning up after the load test.
- Reduce the number of users that will be simulated in the load test. Now it's closer to 1,000.
Test steps:
- Run migration locally and then run a SQL command to delete a user you don't need in your local database

Adjust load test

---

client/components/CreateAccount/CreateAnonymousAccount.jsx
client/components/CreateAccount/index.jsx
client/components/Facilitator/Components/Cohorts/Cohort.jsx
client/components/Login/index.jsx
client/components/Run/index.jsx
client/components/Scenario/index.jsx
client/package.json
server/migrations/20191211151235-inbound-url-params-store-arbitrary-url-params-with-run-responses.js
server/migrations/sql/20191211151235-inbound-url-params-store-arbitrary-url-params-with-run-responses.sql
server/service/runs/endpoints.js
server/service/runs/index.js
yarn.lock

This depends on both "Create Account" and the "local-storage-fallback" update 
(Pick a scenario id to reuse for all of these)
Let COHORT_ID be your preferred cohort's id
Let SCENARIO_ID be your preferred scenario's id
Test 1: 
- Open http://localhost:3000/run/SCENARIO_ID?a=1&b=2
- Use a postrgres tool to run: 
```sql
SELECT * FROM run WHERE referrer_params IS NOT NULL;
```
- If the run has `{a:1,b:2}` stored, then it worked.
- Repeat by starting from logged out and being an anonymous user
Test 2: 
- Open http://localhost:3000/cohort/COHORT_ID/run/SCENARIO_ID?a=1&b=2
- Use a postrgres tool to run: 
```sql
SELECT * FROM run WHERE referrer_params IS NOT NULL;
```
- If the run has `{a:1,b:2}` stored, then it worked.
- Repeat by starting from logged out and being an anonymous user
Test 3: 
- …

Run: capture and save referrer query params

---

client/components/Scenario/ContentSlide.jsx

The "Skip" Button is now gone from slides that contain any required inputs: 
The "Skip" button is still present on slides with inputs that are not marked "required": 
The "Next" button doesn't say "Submit" when there are no things to "submit"

Run: don't show skip button on slides that contain required prompts; fix next slide tip text

---

client/components/Slide/SlideEditor/index.jsx

Fixes: https://app.asana.com/0/1127815256483386/1152537018034518/f
Test 1: 
- Create a scenario
- Add a slide
- Click inside the Slide Title box; you will see the component dropdown close and you can type all the spaces you want. Semantic ui's dropdown has a bug in it that interferes with input boxes, this works around that.

Editor: when the slide title gets focus, close the dropdown to prevent it from interfering with user input in the slide title field

---

client/components/Facilitator/Components/Cohorts/Cohort.css
client/components/Facilitator/Components/Cohorts/CohortScenarios.jsx

https://app.asana.com/0/1127815256483386/1130681121061059/f
Before: 
The description isn't clickable, so we can just hide and only show the scenario title on mobile.

Cohort: scenario list view needs to hide description to make room for scenario title & button

---

server/package.json
yarn.lock

@rwaldron this is the strategy we talked about of moving db-migrate out of dev dependencies.

Move db-migrate packages to production dependencies

---

client/components/ScenarioEditor/index.jsx
client/components/ScenariosList/ScenarioCard.jsx

@rwaldron I'm not 100% sure of the repro steps for this, but when I went to "Continue Moments" as a participant user, I was getting an error that `includes` couldn't run on undefined. I think `categories` should by default be an empty array, so I also tried to account to for the one area where that's not getting save properly. 
Let me know what you think and if you can't repro.

Set default empty array values for scenario categories

---

client/routes/Navigation.jsx
client/routes/Routes.jsx

@rwaldron this PR re-adds the researcher data download view to the nav. 
Test:
- As a user with a researcher role, click on "Research" in the main nav
- Pick a scenario from the dropdown and click "Download CSV"
- Confirm your CSV file downloads and it contains the scenario's participant response data.

Re-add research view to nav

---

client/components/ScenarioEditor/index.jsx
server/service/scenarios/endpoints.js

I noticed that sometimes the Scenario editor renders scenarios before the finish slide is available, even when that scenario has a finish slide. This ensures that doesn't happen. I'm not sure how to test it, as it seemed to happen intermittently, so I suspect there is a race condition in our scenario loading. We can investigate that further at a later time.

Editor: when opening the Scenario Editor, wait until we have finish slide content to render the view

---

client/components/Slide/Components/AudioResponse/Editor.jsx
client/components/Slide/Components/AudioResponse/index.js
client/components/Slide/Components/MultiButtonResponse/Editor.jsx
client/components/Slide/Components/MultiButtonResponse/index.js
client/components/Slide/Components/TextResponse/Editor.jsx
client/components/Slide/SlideEditor/index.jsx

- Adds a "Header" field to all prompt components
- Moves the "Required?" checkbox into the component menu bar (it was confusing before)
https://app.asana.com/0/1127815256483386/1153693807822987/f
https://www.youtube.com/watch?v=VQ-Eh5H8dJY
Test 1: 
1. Add a prompt component, enter a header.
2. Refresh the page and the header value should still be present

Editor: Add "header" field to all "prompt" components

---

client/components/Facilitator/Components/Cohorts/Cohort.jsx
client/components/Facilitator/Components/Cohorts/index.jsx
client/routes/Navigation.jsx
client/routes/Routes.jsx
server/migrations/20191213160505-cohort-participant-can-view-all-own-cohorts.js
server/migrations/sql/20191213160505-cohort-participant-can-view-all-own-cohorts.sql

- Adds "view_own_cohorts" to "participant" (and super admin, where it was oddly missing)
- Removes "My Cohort"
- Participant sees "/cohorts", but only their own cohorts
Test: 
- As a participant, click "Cohorts" and see the cohorts you've received a link to and visited.
- Join more cohorts as a participant, see them all

Cohorts: participants can see all of their own cohorts

---

client/components/Editor/Slides.jsx
client/components/Editor/index.jsx
client/components/Run/index.jsx
client/components/Scenario/Scenario.css
client/components/Scenario/index.jsx
client/components/ScenarioEditor/index.jsx
client/components/ScenariosList/ScenarioCard.jsx
client/routes/RouteComponents.jsx
client/routes/Routes.jsx

Changes: 
- New routes to support urls that enable direct-to-slide access in the slide editor and the slide preview views
- In the Slide Editor: 
- Selecting a slide scrolls that slide to top of the slide list. 
- Adding a new slide scrolls that new slide to top of the slide list. 
- Moving a slide scrolls that slide to top of the slide list. 
- Whatever slide is selected in the Preview pane will be scrolled to the top of the Slide Editor pane.
- In the Preview pane:  
- Selecting a slide scrolls that slide to top of the Preview pane.
- Whatever slide is selected in the Slide Editor pane will be scrolled to the top of the Preview pane.
- Toggling between the Slides and Preview panes keeps the slide index synced
- Excluding the "Entry" and "Finish" slides in Preview pane, since those do …

Editor: active slide index persistence; scroll to active slide between Slides and Preview; support direct to slide URLs

---

server/package.json
server/seed/super-admin.js

@rwaldron this PR allows you to create a super admin user and pass arguments for the user details. An example of how you'd run this command from the root of the project:
`yarn workspace server seed:super-admin email="test@email.com" username="SeedAdmin" password="test"`
This creates a super admin user with the username SeedAdmin, ect. I have a follow up task to document this and permissions stuff already.

Add script and yarn command for seeding a super user

---

client/components/Facilitator/Components/Cohorts/Cohort.css
client/components/Facilitator/Components/Cohorts/CohortScenarios.jsx

https://app.asana.com/0/1127815256483386/1153863291171427/f
Changes: 
- Move the button bar into its own table cell
- Convert the whole cell into a clickable area, but preserve the anchor link
Test: 
- Click anywhere, it should open the scenario

Cohort: Scenario list button uses a whole table cell for a button

---

client/components/Facilitator/Components/Cohorts/CohortDataTable.css
client/components/Facilitator/Components/Cohorts/CohortDataTable.jsx
client/components/Slide/Components/ResponseRecall/Display.jsx
client/components/Slide/Components/Text/Text.css

This builds on https://github.com/bocoup/threeflows/pull/227 and https://github.com/bocoup/threeflows/pull/228, so it must be rebased once those land. 
--------------------------------------------------------------------------------
Pre-test: 
- Log in as a user with Cohort Facilitator role/permissions
- Click "Cohorts" in the top navigation menu, select a cohort that is known to have have run response data
Test 1: 
- Click a Scenario title, once the tab has loaded, click that Scenario's "Download" icon\*
- Observe in the downloaded data that each response cell's contents end with a `(time)`
Test 2: 
- Click a Participant username, once the tab has loaded, click that Participant's "Download" icon\*
- Observe in the downloaded data that each response cell's contents end with a `(time)` …

Cohort: add response duration to data download

---

client/components/Facilitator/Components/Cohorts/CohortScenarios.jsx

Fix for Android not detecting the onClick event. Based on this discussion:
https://github.com/facebook/react/issues/2931
Works on my Pixel 2!

Help clicking on android

---

client/components/Facilitator/Components/Cohorts/index.jsx

- "edit_all_cohorts" is restricted to "super admin" and "admin" and its use here was a mistake.
- "create_cohort" is the correct permission

Cohorts: "create cohort" permission correction

---

client/components/Slide/SlideEditor/index.jsx

Fixes: https://app.asana.com/0/1127815256483386/1152537018034528/f
By adding an explicit ".draggable" class to the elements that should respond to drag, and forcing the Sortable to use its fallback path, the drag response is limited to only elements with the ".draggable" class.
Test 1: 
- Attempt to reproduce reported behavior: 
> 1. Reproduction steps
>     1. Within a slide, add a new element (specifically Participant Suggestion, Text Input Prompt, Multiple Button Prompt, or Audio Response).
>     2. Use your cursor to drag-highlight the placeholder text within the new element.
> 2. Description
>     1. When a new slide element is added, if the mouse cursor is used to highlight placeholder text, it often will cause the whole element box to be moved (in a drag-and-drop way). Sometimes …

Editor: highlighting text with cursor must not drag slide element

---

server/util/sqlHelpers.js

Prevents erroneously typecasting `null` values, because `typeof value === 'object' is true when `value` is `null`, therefore encoding with `::jsonb` even if the field is not a `::jsonb` field. The following JSONB fields are unaffected by this change, for the provided reason: 
- `audio_transcript.response JSONB`, which never receives a `null` value, as it's received from IBM Watson's `SpeechToTextV1` API via `recognize(...)` which responds with a `SpeechRecognitionResults[]` and is never `null`
- `run.referrer_params JSONB`, which never receives a `null` value, as it's _only_ updated when there are non-null/non-undefined values, which are always initialized with `{}` (via `JSON.parse()` or `QueryString.parse()`)
- `run_response.response JSONB`, which never receives a `null` value, as it's …

SQL: when encoding queries, don't accidentally typecast null to jsonb

---

client/components/ScenarioEditor/DropdownOptions.jsx
client/components/ScenarioEditor/index.jsx
client/reducers/scenario.js
server/service/roles/db.js
server/service/roles/endpoints.js
server/service/roles/index.js
server/service/scenarios/db.js
server/service/scenarios/endpoints.js

Proposed changes:
- Add drop down in the "Scenario" tab for setting the Scenario's author
- Add API endpoint for getting all users that have authoring privileges
- In the API, add a check for an author username when adding or updating a scenario and if set, use that author's ID
Test 1: 
- Create a new scenario (can be admin user or not)
- Fill in just the title and description, hit save
- Observe the logged in user is the author as a default if one isn't set
Test 2:
- As an admin, create a new scenario
- Choose an author different from your username and save
- Observe that new scenario has the author you chose
Test 3:
- Edit an existing scenario
- Change the author and hit save
- Refresh the editor and confirm that your author change has saved

Add dropdown for admin users to change scenario authors

---

client/components/ScenariosList/ScenarioEntries.jsx

When logged in as the author of all the scenarios, I can see every scenario I've authored, including "Draft", "Public" and "Private":
When logged in as someone else, that is not the author, I can see scenarios that are marked "Private": 
When logged out, I can only see scenarios that have been marked as "Public":

ScenarioList: scenario lists should respect scenario status.

---

heroku-server.js
package.json
yarn.lock

This PR uses a library to redirect http requests to https. It turns out that [Heroku doesn't have a built in force-https setting](https://help.heroku.com/J2R1S4T8/can-heroku-force-an-application-to-use-ssl-tls) and they actually recommend using a library. I saw that this one was recommended in a couple places.
Adding the library to the heroku-server.js file will prevent it from affecting our local development environments. To test it locally however, you can run `node heroku-server.js` and visit the site at http://localhost:5000. You will then see that you're redirected to https.

Force SSL for the Heroku server

---

client/components/AccountAdmin/index.jsx
client/components/Facilitator/Components/Cohorts/CohortScenarios.jsx
server/service/cohort/index.js
server/service/roles/index.js
server/service/roles/middleware.js

@rwaldron I think more auth check PRs are coming, but didn't want to make them too big. My proposed changes:
- Small amount of refactoring to AccountAdmin
- In CohortScenarios, make sure facilitators and researchers can add scenarios to their cohorts (they should be able to, right?)
- Specify required roles for the cohorts API routes (especially good to confirm I understood their intended roles right)
- Specify required roles for roles API
Tests:
- As an admin confirm you can edit roles in Account Administration
- As a researcher or facilitator confirm you can create and edit your cohort
- As a participant, make sure you can still join cohorts

Add cohorts and roles auth checks

---

server/service/scenarios/index.js
server/service/scenarios/slides/index.js

@rwaldron this is a follow up to the API auth checks. My proposed changes are to make sure only roles with scenario create permissions should be able to hit certain endpoints. 
Tests:
- As an admin, perform all CRUD operations with a scenario and also slides with in it
- As an facilitator or researcher, perform all CRUD operations with a scenario and also slides with in it

Add auth checks for scenario CRUD operations

---

client/components/AccountAdmin/UserRows.jsx
client/components/AccountAdmin/index.jsx

If a user doesn't at least have Participant role permissions, they cannot do or see anything in the application.

Account Administration: make it impossible to remove "Participant" permissions from any user

---

client/components/Scenario/Scenario.css

https://app.asana.com/0/1127815256483386/1152537018034552/f
The default font-size from body {} is 14px. This changes that to 16px

Scenario Run: Default body text appears small

---

client/static/root-styles.css

Since body is `14px`, `font-size: 1.1456em !important;` is approximately 16px.

Input font size for mobile

---

client/static/index.html

This will prevent Chrome from erroneously attempting to translate the page

Explicitly set the default application language

---

client/components/Editor/index.jsx
client/components/EditorMenu/EditorMenu.css
client/components/EditorMenu/index.jsx
client/components/Facilitator/Components/Cohorts/Cohort.css
client/components/Facilitator/Components/Cohorts/CohortCard.jsx
client/components/Facilitator/Components/Cohorts/index.jsx
client/components/ScenarioEditor/DropdownOptions.jsx
client/components/ScenarioEditor/index.jsx
client/components/ScenariosList/ScenariosList.css
client/components/ScenariosList/index.jsx
client/reducers/scenario.js
client/routes/Navigation.jsx
server/service/auth/db.js
server/service/roles/endpoints.js
server/service/scenarios/db.js
server/service/scenarios/endpoints.js

Most notable changes: 
- The "Create a Scenario" menu item didn't really belong in the main menu; that's not moved into "Scenarios" view (matches "Cohorts")
- "Scenarios" view has a new "search" capability (matches "Cohorts")

ScenarioList: organizing into a "create" and "search" feature for "Scenarios" view
