bocoup/threeflows

config/pg.dev, package.json
Windows doesn't seem to like `;` in the commands so replaced with some `&&` and then canceling some error conditions with `||`
=> Some tweaks to get things clear on windows too

.eslintrc.json, src/client/components/login/index.jsx
Fixes some small bugs I found after merging in the Redux PR
=> Fix some small bugs and add console linting

src/client/components/login/index.jsx, src/client/reducers/login.js, src/server/index.js, src/server/util/authenticationHelpers.js
@gnarf @evmiguel this PR hooks up our login route to the login page UI! If you have a passwordless user, you can put their username in the input field, hit login, and be logged in. If there are any login errors, they will display on the page.
=> Hookup username sign-in to UI

.gitignore
This is a quick one @evmiguel @gnarf to prevent accidental commits of raw data to the repo. Garron mentioned this had been an issue in the past and requested we add something to prevent it in our re-write. Let me know if there are other data formats you can think of! I decided it didn't make sense to include json files since we use them throughout the repo ourselves.
=> Prevent commiting raw data to the repo

src/server/service/roles/db.js, src/server/util/db.js
@gnarf This is a quick one to replace all the places we have a typo in the function name.
=> Fix function name typo

client/routes/index.jsx
Small language change @gnarf @isaacdurazo !
=> Change nav text

client/components/Slide/Components/Text/Editor.jsx, client/package.json, yarn.lock
This also gives us human readable names for font formatting, eg. "Heading 1" instead of "H1". 
Here's the component's docs for further information: http://www.nibedit.com/index.html
=> Editor: migrate react-draft-wysiwyg => nib

package.json
Changing deploy branch from staging-site to teacher-moments
=> changing branch from staging-site to teacher-moments

client/components/Editor/Slides.css, client/components/Editor/Slides.jsx, server/service/scenarios/slides/endpoints.js
=> Add ability to re-order slides with buttons

client/components/Editor/Slides.jsx
This is a small update to make sure users know when a slide has been successfully added to their scenario.
=> Add 'slide added' message

client/components/ScenariosList/index.jsx
This PR only handles the grid format. Hover functionality in another PR.
=> Moments list redesign grid

client/actions/index.js, client/actions/types.js, client/components/Editor/Slides.jsx, client/components/Editor/index.jsx, client/components/Scenario/index.jsx, client/components/ScenariosList/index.jsx, client/components/Slide/Components/AudioResponse/Display.jsx, client/components/Slide/Components/CheckResponse/Display.jsx, client/components/Slide/Components/Text/Display.jsx, client/components/Slide/Components/TextResponse/Display.jsx, client/components/Slide/Editor/index.jsx, client/components/SlideList/SlideList.css, client/components/SlideList/index.jsx, client/reducers/scenario.js, client/routes/index.jsx
@gnarf @evmiguel @rwaldron here is my PR for getting started on viewing a scenario on the front end! My proposed changes:
- Add a route and component `Scenario` for viewing a single scenario
- Refactor a small bit of the slides into `SlidesList` and use that in `Scenario` and in the editor
- Add a link to the home page to click on the title of a scenario and view it
- Add a preview tab to the editor to see the scenario once it has been saved
Let me know what you think!
=> Scenario front end

client/components/Facilitator/Components/Dashboard/index.jsx, client/components/Facilitator/Components/Search/SearchResults.jsx, client/components/Facilitator/Components/Search/index.jsx, client/components/Facilitator/index.jsx
Nothing about the rendered layout is changed here, just the markup pattern. Once this is made consistent, we should revisit the pattern and see if it can be further simplified.
=> Facilitator: fix layout markup to match Editor view

client/components/Editor/Slides.jsx, client/components/ScenarioEditor/index.jsx
This is just a basic sketch out for what needs to be done to complete this feature once the API is updated. Nothing presently blocking this and changes can/should be made in the follow up that @evmiguel will producing.
=> ScenarioEditor: basic scenario tagging ui scaffold.

client/components/ScenarioEditor/index.jsx
=> ScenarioEditor: resize per agreement made for previously merged PR

client/components/Editor/Slides.jsx, client/components/Slide/Editor/index.jsx
=> Slide Editor: close gap between slides list and editor area

client/components/ScenarioEditor/index.jsx, server/migrations/20191030134441-categories-topics-views.js, server/migrations/sql/20191030134441-categories-topics-views.sql, server/service/scenarios/db.js, server/service/scenarios/endpoints.js, server/service/tags/db.js
This PR integrated the tags database architecture to the front end with persistence.
[DEMO VIDEO](https://drive.google.com/file/d/14lv7HdLFE9MO4UAun8elQlQmqTBhkH0y/view?usp=sharing)
=> integrating categories list to front end

client/components/CreateAccount/index.jsx, client/components/Login/index.jsx
Re: https://app.asana.com/0/1127815256483386/1127982138529123/f
=> Create Account: allow new accounts to be created without an email address

client/components/Editor/ConfirmableDeleteButton.jsx, client/components/Editor/Slides.jsx, client/components/Editor/index.jsx, client/components/EditorMenu/index.jsx, client/components/Slide/Editor/index.jsx, server/service/scenarios/db.js
=> Moment Editor: save and delete buttons in new scenario-wide menu

client/components/EditorMenu/index.jsx, client/components/Slide/Components/AudioResponse/Card.jsx, client/components/Slide/Components/CheckResponse/Card.jsx, client/components/Slide/Components/Text/Card.jsx, client/components/Slide/Components/TextResponse/Card.jsx, client/components/Slide/Editor/index.jsx
=> Editor/Slides: Add displayed labels for all slide components.

client/components/Editor/Slides.jsx
=> Editor/Slides: change "Add slides" dropdown to a simple "Add slide" button

client/components/Editor/index.jsx
https://app.asana.com/0/1127815256483386/1145707742372472/f
=> Editor: when editing a moment, move "Moment" to "Slides" tab

client/components/Editor/Slides.css, client/components/Editor/Slides.jsx, client/components/Editor/editor.css, client/components/Editor/index.jsx, client/components/Facilitator/Components/Dashboard/index.jsx, client/components/Facilitator/Components/Search/index.jsx, client/components/ScenarioEditor/index.jsx, client/components/Slide/Components/Text/Card.jsx, client/components/Slide/Components/Text/Editor.jsx, client/components/Slide/Editor/Editor.css, client/components/Slide/Editor/index.jsx
=> Slide list scrollable container

client/components/Editor/Slides.css, client/components/Editor/Slides.jsx, client/components/Slide/Components/Text/Editor.jsx, client/components/Slide/Editor/Editor.css, client/components/Slide/Editor/index.jsx
=> Editor: fixes various height and width issues in editor and slides list

client/components/ScenariosList/index.jsx
=> ScenarioList: layout cleanup with Card.Group + Card

client/components/ScenariosList/index.jsx, client/routes/index.jsx, server/service/scenarios/db.js
[DEMO](https://drive.google.com/file/d/1qm32e3sUcAQHIv-deACTWTv9rIUFU7H7/view?usp=sharing)
=> filtering scenarios by categories provided by backend

README.md
@evmiguel these were some small details I've been meaning to add to the deployment section of the README based on our recent walk through it. Let me know what you think!
=> Add some detail to deployment docs

server/service/auth/db.js, server/service/roles/db.js, server/service/roles/endpoints.js, server/service/roles/index.js
@gnarf @evmiguel @rwaldron this PR refactors the roles API a bit and adds a route I need for the user admin UI for getting all users. I figured reviewing these separately from the front end might be a little easier. I also moved `getUserById` to the roles service since that is the only place it's used. 
Let me know what you think!
=> Refactor roles API and add get all users endpoint

client/components/Editor/Slides.css, client/components/Editor/Slides.jsx
=> Editor/Slides: Options -> Duplicate slide.

client/components/Slide/Components/Suggestion/Card.jsx, client/components/Slide/Components/Suggestion/Display.jsx, client/components/Slide/Components/Suggestion/Editor.jsx, client/components/Slide/Components/Suggestion/index.js, client/components/Slide/Components/Suggestion/type.js, client/components/Slide/Components/Text/Editor.jsx, client/components/Slide/Components/index.js, client/components/Slide/Editor/index.jsx
=> Slide Suggestion: add "suggestions" to a slide.

client/components/EditorMenu/ConfirmableDeleteButton.jsx, client/components/EditorMenu/index.jsx, client/components/Slide/Editor/index.jsx, client/components/SlideComponentsList/index.jsx
Here's the preview/edit switch: 
https://youtu.be/aD_v0NEljmI
=> EditorMenu: popup labels + "editable" control

client/components/Editor/Slides.css, client/components/Editor/Slides.jsx, client/components/Editor/index.jsx, client/components/ScenarioEditor/index.jsx, client/components/Slide/Editor/index.jsx, client/reducers/scenario.js
- Don't show slide options when there are no slides in a scenario
- Prompts to add slides
- Prompts to add content
- Better Slide activity messages
- Icon popups
=> Editor: tweaks to improve first time use

README.md, server/index.js
use the session secret from an environment variable
=> session secret

client/components/Run/index.jsx, client/components/Scenario/index.jsx, client/components/ScenariosList/index.jsx, client/routes/index.jsx, server/service/runs/endpoints.js
This PR adds a run button and writes to the run table for a given scenario. I need this route to be able to handle responses. [DEMO](https://drive.google.com/file/d/13iTJ783NL9X4RK-BZbGmpNko7Oea4xNN/view?usp=sharing)
------
[UPDATED DEMO](https://drive.google.com/file/d/1GI87DFSgTprsi4l3COEVyi9EJwl-i111/view?usp=sharing)
=> adding run route

client/components/Editor/index.jsx, client/routes/index.jsx
Fixes https://app.asana.com/0/1127815256483386/1145881120386969/f
=> Editor: Clicking "Create a moment" from the Editor produces a blank project

client/components/Editor/Slides.css, client/components/Editor/editor.css, client/components/Slide/Editor/Editor.css, client/routes/index.jsx
This is built on top of https://github.com/bocoup/threeflows/pull/125, and will need to be rebased once that lands
=> Reduce header menu

client/static/index.html
Pretty small and self-explanatory, but let me know if you have any questions @rwaldron @evmiguel!
=> Set viewport to allow for mobile responsiveness

client/components/Run/index.jsx, client/components/Scenario/index.jsx, client/components/Slide/Components/AudioResponse/Display.jsx, client/components/SlideComponentsList/index.jsx, client/package.json, config/dev, server/package.json, server/service/media/endpoints.js, server/service/media/index.js, server/service/media/s3.js, yarn.lock
[DEMO](https://drive.google.com/file/d/1p1p4eCSHwPdMfP6FC2yLzyGU0PtFwJqC/view?usp=sharing)
=> full stack save audio response as mp3

client/components/Scenario/ContentSlide.jsx
=> Participant Run: "Skip" button which records a generic response "Participant Skipped" for the given prompt

client/components/Login/ConfirmableLogoutMenuItem.css, client/components/Login/ConfirmableLogoutMenuItem.jsx, client/components/Login/index.jsx, client/routes/Navigation.jsx, client/routes/Routes.jsx
Also fixes the strange "must click log out twice" by providing a prompt to confirm logout instead of rendering the whole page.
=> Login/Logout: correct page state by forcing a real request of the page on success of either operation

client/components/Run/index.jsx, client/components/Scenario/ContentSlide.jsx, client/components/Slide/Components/AudioResponse/Display.jsx, client/components/Slide/Components/AudioResponse/Editor.jsx, client/components/Slide/Components/MultiButtonResponse/Display.jsx, client/components/Slide/Components/ResponseRecall/Display.jsx, client/components/Slide/Components/TextResponse/Display.jsx, server/service/runs/endpoints.js
=> Participant Run: simplify response, don't pave over responses with a skip, adds isSkip property to responses

client/routes/Nav.css, client/routes/Navigation.jsx
Here is what this looks like: 
big:
small:
=> adds logo to menu

client/routes/Navigation.jsx, client/routes/Routes.jsx
This is not really meant to be merged, but more as a conversation about what the ui nav items should be labeled as:
* I think "cohort management" makes more sense than "facilitator" at this point.
* I think "Moments" makes more sense than "curated"
* I think "researcher" needs to be merged in as a sub-view of "cohorts".
Does this make sense?
=> experimenting with menu changes

client/reducers/scenario.js
https://app.asana.com/0/1127815256483386/1130681121061057/f
=> Scenario: add consent to initialState

client/components/Scenario/Scenario.css, client/components/Scenario/index.jsx
=> Scenario: make preview pane scrollable to keep menu in view while editing

client/components/Slide/Components/AudioResponse/Display.jsx, client/components/Slide/Components/AudioResponse/Editor.jsx, client/components/Slide/Components/AudioResponse/index.js, client/components/Slide/Components/MultiButtonResponse/Display.jsx, client/components/Slide/Components/MultiButtonResponse/Editor.jsx, client/components/Slide/Components/MultiButtonResponse/index.js, client/components/Slide/Components/ResponseRecall/Display.jsx, client/components/Slide/Components/ResponseRecall/Editor.jsx, client/components/Slide/Components/TextResponse/Display.jsx, client/components/Slide/Components/TextResponse/Editor.jsx, client/components/Slide/Components/TextResponse/index.js, client/components/Slide/SlideEditor/SlideEditor.css, client/components/SlideComponentsList/index.jsx
=> Link response recall to another response

client/components/Scenario/EntrySlide.css, client/components/Scenario/EntrySlide.jsx
=> EntrySlide: overflow scrolling; disable revocable consent

client/components/ScenariosList/DeletedCard.jsx, client/components/ScenariosList/ScenarioCard.jsx, client/components/ScenariosList/ScenariosList.css
=> Moment: set max-height and overflow-y on overlong descriptions

client/components/Slide/Components/Suggestion/Display.jsx, client/components/Slide/Components/Suggestion/Editor.jsx
~~Depends on https://github.com/bocoup/threeflows/pull/155~~
=> Toggle suggestions sections

.eslintignore, client/components/ScenariosList/ScenarioCard.jsx
@rwaldron this fixes the user auth issue here: https://app.asana.com/0/1127815256483386/1152294787700553
It also re-creates your node_modules linting fix, since I don't think that's made it into the codebase yet and it throwing off my linting.
=> Check auth for scenario copying

client/components/Slide/Components/AudioResponse/AudioResponse.css, client/components/Slide/Components/AudioResponse/Display.jsx, client/components/Slide/Components/ResponseRecall/Display.jsx, server/migrations/20191206023307-audio-transcript.js, server/migrations/sql/20191206023307-audio-transcript.sql, server/package.json, server/service/media/db.js, server/service/media/endpoints.js, server/service/media/transcript.js, server/service/runs/db.js, server/service/runs/endpoints.js, yarn.lock
1. Go to heroku and get these: `WATSON_KEY` and `WATSON_URL`. 
1. Run the migration
1. Export them as env vars in your local environment, and restart the application 
1. Record an audio response. If everything goes according to plan, it will be transcribed. Check back on that slide to see if it worked.
=> Transcribe audio responses

client/components/Editor/Slides.jsx, client/components/Editor/index.jsx, client/components/Scenario/ContentSlide.jsx, client/components/Scenario/FinishSlide.jsx, client/components/Scenario/Scenario.css, client/components/Scenario/index.jsx, client/components/ScenarioEditor/index.jsx, client/components/ScenarioEditor/scenarioEditor.css, client/components/Slide/Components/AudioResponse/Display.jsx, client/components/Slide/Components/MultiButtonResponse/Display.jsx, client/components/Slide/Components/ResponseRecall/Display.jsx, client/components/Slide/Components/Text/Editor.jsx, client/components/Slide/Components/TextResponse/Display.jsx, client/reducers/scenario.js, server/migrations/20191204171924-scenario-slide-is_finish.js, server/migrations/sql/20191204171924-scenario-slide-is_finish.sql, server/service/scenarios/db.js, server/service/scenarios/endpoints.js, server/service/scenarios/slides/db.js, server/service/scenarios/slides/endpoints.js
I built this off the prompt branch, because there are changes there that I needed here.
=> Static finish slide

client/components/Facilitator/Components/Cohorts/Cohort.jsx, client/components/Facilitator/Components/Cohorts/CohortScenarios.jsx
Compare
Facilitator view: 
Participant view:
=> Participant View: hide unfinished ui elements

server/service/scenarios/db.js
For _legacy_ scenarios that get deleted, it will appear as though "restore" button doesn't work, but it does... there is just an error that occurs _after_ the scenario is restored, causing the client to appear unresponsive
=> Fix: Legacy Scenarios that are missing a "finish" slide will produce 500 errors when attempting to restore them.

client/components/Slide/Components/Text/index.js
https://app.asana.com/0/1127815256483386/1152537018034520/f
=> Slide Editor: remove default text from rich text editor.

client/components/Slide/Components/Text/Editor.jsx, client/package.json, yarn.lock
https://app.asana.com/0/1127815256483386/1152537018034513/f
=> Bug: No Support for Line Breaks in Text

client/components/Facilitator/Components/Cohorts/Cohort.jsx, client/components/Facilitator/Components/Cohorts/CohortDataTableMenu.jsx
This PR adds a scenarios data view for a participant when they visit "My Cohorts"
=> Add cohort data view for participants

client/components/Facilitator/Components/Cohorts/CohortDataTable.jsx, client/components/Facilitator/Components/Cohorts/CohortDataTableMenu.jsx, server/service/cohort/db.js
=> Cohort: data download from scenarios and participants.

client/components/Login/index.jsx, client/routes/RouteComponents.jsx, client/routes/Routes.jsx, server/migrations/20191210194013-unique-username-constraint.js, server/migrations/sql/20191210194013-unique-username-constraint.sql, server/service/auth/db.js
https://www.youtube.com/watch?v=dXVvq3UTF6Y
=> Create Account: make consistent with other create account paths, enforce unique usernames with table constraint

client/components/Facilitator/Components/Cohorts/Cohort.jsx
https://www.youtube.com/watch?v=cfNGA3PD0Ac&feature=youtu.be
This depends on https://github.com/bocoup/threeflows/pull/198 and will need to be rebased after that lands
=> Cohorts: persist cohort data tabs

client/components/Slide/Components/Text/Display.jsx, client/components/Slide/Components/Text/Text.css
=> Text: constrain image display to within the card boundary

client/components/Facilitator/Components/Cohorts/CohortDataTable.jsx
=> Cohort Participant Data: don't leave the loading spinner when there's no data to display

client/components/Slide/Components/AudioResponse/Editor.jsx, client/components/Slide/Components/MultiButtonResponse/Editor.jsx, client/components/Slide/Components/TextResponse/Editor.jsx
https://app.asana.com/0/1127815256483386/1153863291171425/f
=> Editor: rename "Header" to "Data Header"

client/util/session.js
Test: 
- View a cohort, open data tabs
- Log out
- Log back in as another user
- View the same cohort, see that there are no open data tabs
=> Clear localstorage on logout

client/components/Facilitator/Components/Cohorts/CohortDataTable.css, client/components/Facilitator/Components/Cohorts/CohortDataTable.jsx, client/package.json, server/service/cohort/endpoints.js, server/service/scenarios/slides/endpoints.js, server/service/scenarios/slides/index.js, yarn.lock
This depends on changes introduced in https://github.com/bocoup/threeflows/pull/219
Test: 
- Open a cohort that has accumulated scenario Runs
- Click on the "View cohort responses" icon
- When the table loads, click a cell. 
- Confirm that you see something like this:
=> Cohort prompt data detail view

client/routes/Navigation.jsx
=> Navigation: move "My Scenario Data" into "authorizedNav" with "view_own_data" permission

client/components/Slide/Components/Text/Editor.jsx, client/package.json, yarn.lock
Adding ?rel=0 to the end of the url will achieve:
1. prevent the panel of 9 random videos from appearing
2. show two videos that are from the same video publisher
Which is the only option that we have for now
=> "Sort of" Prevent Suggested Video from displaying on player

client/components/Slide/Components/MultiButtonResponse/Editor.jsx
https://app.asana.com/0/1127815256483386/1154637627808065/f
Pre-test: 
- Create a new scenario or open an existing scenario in the slide editor.
- Add a slide
Test 1: 
- Add a multi button prompt
- Add a button, type "foo" in the display. Leave the input by tabbing
- Observe that the value is updated to "foo"
Test 2: 
- Add a multi button prompt
- Add a button, type "foo" in the display. Leave the input by clicking in another input
- Observe that the value is updated to "foo"
Test 3: 
- Add a multi button prompt
- Add a button, type "foo" in the display. Leave the input by clicking anywhere on the screen
- Observe that the value is updated to "foo"
Test 4: 
- Add a multi button prompt
- Add a button, type "foo" in the **value**. Leave the input by tabbing
- Observe that the **display** is …
=> Editor: prevent empty button value

client/components/Slide/Components/AudioResponse/Editor.jsx, client/components/Slide/Components/MultiButtonResponse/Editor.jsx, client/components/Slide/Components/TextResponse/Editor.jsx
https://app.asana.com/0/1127815256483386/1154637627808060/f
Pre-test: 
- Create a new scenario or open an existing scenario in the slide editor.
- Add a slide
Test 1: 
- Add any prompt component
- Uncheck "Required?"
- Enter any input field and change the contents (prompt, placeholder, header, etc)
- Observe that "Required?" remains unchecked
Test 2: 
- ...With the same prompt component...
- Check "Required?"
- Enter any input field and change the contents (prompt, placeholder, header, etc)
- Observe that "Required?" remains checked
=> SlideEditor/Components/*/Editor: "required" is tracked by SlideEditor, not within component editor

client/routes/RouteComponents.jsx, client/routes/Routes.jsx
I believe this can/should be applied to other routes, but I don't have time at the moment for a full assessment.
=> RedirectRouteForInactiveSession: don't allow logged out users to reach "MyScenarios"; redirect to log in

client/components/ClickableTableCell/index.jsx, client/components/Facilitator/Components/Cohorts/CohortScenarios.jsx, client/components/MyScenarios/index.jsx
Pre-test: 
- When logged in a user that has both independent and cohort run history
Test 1: 
- Click "My Scenario Data" in the navigation
- Observe that you can see which runs were in a cohort and which were not.
For example:
=> MyScenarios: Include link to cohort if scenario run is from a cohort

client/index.js, client/package.json, client/postcss.config.js, client/routes/Nav.css, client/routes/Navigation.jsx, client/static/index.html, client/webpack.config.js, yarn.lock
- DCSS_BRAND_NAME_TITLE
- DCSS_BRAND_LOGO
Test 1: 
- Shut down the dev server and restart it with these env vars: 
```
export DCSS_BRAND_NAME_TITLE="Brand X"; 
export DCSS_BRAND_LOGO=https://i.gyazo.com/31620e1b55c69532e6057c8161171688.png;
```
For example: 
```
DCSS_BRAND_NAME_TITLE="Brand X"; 
DCSS_BRAND_LOGO=https://i.gyazo.com/31620e1b55c69532e6057c8161171688.png; SQL_DEBUG=1 yarn dev
```
Will produce:
=> Private Label: implement a set of env vars that can be used to override 'branding' elements

server/util/db.js, server/util/dbConfig.js
@TheGarron here's the patch that I described via email.
=> DB: Normalize on connectionString for all deployed application db connections (production and staging)
